[tool.poetry]
version = "0.0.0"
name = "test_panda_pypi"
authors = ["Shawn Hu <shawnhu97@gmail.com>"]
description = "A small example package of adding 2 numbers together"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[tool.poetry.urls]
Homepage = "https://github.com/TheFatPanda97/test-pypi"
Issues = "https://github.com/TheFatPanda97/test-pypi/issues"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
test-panda = "test_panda_pypi:main"
